/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsBankWireDisputeRouteImport } from './routes/workflows/bank-wire-dispute'
import { Route as WorkflowsContractorDisputeRouteImport } from './routes/workflows/contractor-dispute'
import { Route as WorkflowsPropertyInsuranceClaimRouteImport } from './routes/workflows/property-insurance-claim'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsBankWireDisputeRoute =
  WorkflowsBankWireDisputeRouteImport.update({
    id: '/workflows/bank-wire-dispute',
    path: '/workflows/bank-wire-dispute',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsContractorDisputeRoute =
  WorkflowsContractorDisputeRouteImport.update({
    id: '/workflows/contractor-dispute',
    path: '/workflows/contractor-dispute',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsPropertyInsuranceClaimRoute =
  WorkflowsPropertyInsuranceClaimRouteImport.update({
    id: '/workflows/property-insurance-claim',
    path: '/workflows/property-insurance-claim',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/workflows/bank-wire-dispute': typeof WorkflowsBankWireDisputeRoute
  '/workflows/contractor-dispute': typeof WorkflowsContractorDisputeRoute
  '/workflows/property-insurance-claim': typeof WorkflowsPropertyInsuranceClaimRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/workflows/bank-wire-dispute': typeof WorkflowsBankWireDisputeRoute
  '/workflows/contractor-dispute': typeof WorkflowsContractorDisputeRoute
  '/workflows/property-insurance-claim': typeof WorkflowsPropertyInsuranceClaimRoute
  '/workflows': typeof WorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/workflows/bank-wire-dispute': typeof WorkflowsBankWireDisputeRoute
  '/workflows/contractor-dispute': typeof WorkflowsContractorDisputeRoute
  '/workflows/property-insurance-claim': typeof WorkflowsPropertyInsuranceClaimRoute
  '/workflows/': typeof WorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/workflows/bank-wire-dispute'
    | '/workflows/contractor-dispute'
    | '/workflows/property-insurance-claim'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/workflows/bank-wire-dispute'
    | '/workflows/contractor-dispute'
    | '/workflows/property-insurance-claim'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/workflows/bank-wire-dispute'
    | '/workflows/contractor-dispute'
    | '/workflows/property-insurance-claim'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  WorkflowsBankWireDisputeRoute: typeof WorkflowsBankWireDisputeRoute
  WorkflowsContractorDisputeRoute: typeof WorkflowsContractorDisputeRoute
  WorkflowsPropertyInsuranceClaimRoute: typeof WorkflowsPropertyInsuranceClaimRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/bank-wire-dispute': {
      id: '/workflows/bank-wire-dispute'
      path: '/workflows/bank-wire-dispute'
      fullPath: '/workflows/bank-wire-dispute'
      preLoaderRoute: typeof WorkflowsBankWireDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/contractor-dispute': {
      id: '/workflows/contractor-dispute'
      path: '/workflows/contractor-dispute'
      fullPath: '/workflows/contractor-dispute'
      preLoaderRoute: typeof WorkflowsContractorDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/property-insurance-claim': {
      id: '/workflows/property-insurance-claim'
      path: '/workflows/property-insurance-claim'
      fullPath: '/workflows/property-insurance-claim'
      preLoaderRoute: typeof WorkflowsPropertyInsuranceClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  WorkflowsBankWireDisputeRoute: WorkflowsBankWireDisputeRoute,
  WorkflowsContractorDisputeRoute: WorkflowsContractorDisputeRoute,
  WorkflowsPropertyInsuranceClaimRoute: WorkflowsPropertyInsuranceClaimRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
